### ISSUE TITLE
Error with pod install command

### ISSUE THREAD

**Issue by josmmv** [sayem314/react-native-keep-awake#8]
When I run the command `RCT_NEW_ARCH_ENABLED=1 pod install` in the ios folder, I get this error:

```cmd
[!] Invalid `Podfile` file: 
[!] Invalid `react-native-keep-awake.podspec` file: undefined local variable or method `folly_compiler_flags' for Pod:Module.

 #  from /.../node_modules/@sayem314/react-native-keep-awake/react-native-keep-awake.podspec:24
 #  -------------------------------------------
 #    if ENV["RCT_NEW_ARCH_ENABLED"] == "1"
 >      s.compiler_flags = folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED=1"
 #      s.pod_target_xcconfig    = {
```

**Comment by ErHarinderSingh** [comment]
@josmmv @sayem314 same here.

**Comment by sayem314** [comment]
@zabojad can you please take a look at this?

**Comment by zabojad** [comment]
@ErHarinderSingh @josmmv I dont have that with RN 0.71.10

What version of RN are you using?

**Comment by zabojad** [comment]
OK, I've found the problem, it will happen on any RN version <= 0.70.

I'll issue a PR ti fix that.

**Comment by zabojad** [comment]
the PR is open...

**Comment by sayem314** [comment]
@zabojad, thank you for the prompt resolution.

@josmmv and @ErHarinderSingh, could you please review the new version 1.2.1 and provide us with your feedback?

**Comment by ErHarinderSingh** [comment]
Hi @sayem314 , @zabojad  thanks for your solution. It's working fine as no error shown now. My build is not compiling right now as I am using **[react-native-share](https://github.com/react-native-share/react-native-share)** library and it also has same error. 
Can we refer this fix to them as well?

**Comment by zabojad** [comment]
@ErHarinderSingh I'll issue a PR on react-native-share as well...

**Comment by zabojad** [comment]
@ErHarinderSingh here you go => https://github.com/react-native-share/react-native-share/pull/1417

**Comment by ErHarinderSingh** [comment]
@zabojad @sayem314 
Now compile time issues.
<img width="1498" alt="Screenshot 2023-07-06 at 21 11 33" src="https://github.com/sayem314/react-native-keep-awake/assets/22139572/5458e48e-81b4-4dea-9af3-dfd84f797ea2">

**Comment by zabojad** [comment]
@ErHarinderSingh what version of react native are you using ?

**Comment by ErHarinderSingh** [comment]
@zabojad I am using 0.72.1 latest

**Comment by zabojad** [comment]
@ErHarinderSingh I've just created a new 0.72.1 project, added `react-native-keep-awake`, did `RCT_NEW_ARCH_ENABLED=1 pod install` and ran it on device. It compiled and ran without any problem...

You might try to clean the build folder in XCode and retry to compile it...

**Comment by ErHarinderSingh** [comment]
No it's not working. I tried all the ways, reinstall pods after deleting Podfile.lock file, clear build folder from xcode.
From CLI I am getting below error.

<img width="794" alt="Screenshot 2023-07-07 at 14 39 38" src="https://github.com/sayem314/react-native-keep-awake/assets/22139572/b78a50e0-7617-4c04-ac5e-c10025fc8caa">

**Comment by zabojad** [comment]
Can you try compiling/running on a real device 🤔 ?

**Comment by ErHarinderSingh** [comment]
@zabojad @sayem314 same error.

**Comment by zabojad** [comment]
@ErHarinderSingh can you share your application podfile ? Is there anything you've customized there?

**Comment by zabojad** [comment]
@ErHarinderSingh Can you also please share the output of `npx react-native info` ?

**Comment by ErHarinderSingh** [comment]
<img width="1109" alt="Screenshot 2023-07-07 at 21 37 02" src="https://github.com/sayem314/react-native-keep-awake/assets/22139572/adf865f3-17b6-44f2-953d-ad10bf469cc7">

**Comment by zabojad** [comment]
@josmmv Is the issue fixed at your end ?

@ErHarinderSingh I don't get it... I don't reproduce that error at my end and I tried. 

I've also checked if the classes `NativeKCKeepAwakeSpec` and `NativeKCKeepAwakeSpecJSI` are actually generated by codeGen and they actually are:

<img width="972" alt="Screenshot 2023-07-07 at 22 10 05" src="https://github.com/sayem314/react-native-keep-awake/assets/1238030/3d427368-2c4f-486e-999e-fecb8f69cc3b">

**Comment by zabojad** [comment]
@ErHarinderSingh thinking about that now, it would be interesting to see what codeGen does at your end.

Can you please show us what it generates in your project when you do this:

```sh
cd <path/to/your/app>
node node_modules/react-native/scripts/generate-codegen-artifacts.js \
    --path <your app>/ \
    --outputPath <an/output/path> \
```

**Comment by ErHarinderSingh** [comment]
Can we connect somehow on zoom or something else? I think that way you can find your bug easily.
@zabojad @sayem314 ?

**Comment by ErHarinderSingh** [comment]
Hi @zabojad , @sayem314 it also happened on fresh project for me.
Steps : 
`npx react-native init d`
`cd d`
`yarn add @sayem314/react-native-keep-awake`
`cd ios && bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install && cd ..`
`npx react-native run-ios --simulator="iPhone 14 Pro" `

Still facing this error; strange.

<img width="682" alt="Screenshot 2023-07-08 at 12 53 59" src="https://github.com/sayem314/react-native-keep-awake/assets/22139572/59508c03-1196-4392-b77c-03b0846b8f14">

**Comment by ErHarinderSingh** [comment]
Hi @zabojad @sayem314 , Now I deleted xCode & reinstalled it but still that same errors. Strange.

**Comment by zabojad** [comment]
Hi @ErHarinderSingh !

I've just reproduced the problem by installing the npm version of `@sayem314/react-native-keep-awake` instead of my local version...

I thus can investigate on this. I keep you updated as soon as I've found why it's happening...

**Comment by zabojad** [comment]
OK, I've found the cause of the problem: codeGen doesn't generate the JSI classes because of this commit: https://github.com/sayem314/react-native-keep-awake/commit/5a22a8f26fc37aee54ebea0a1167b0710c8d3635

@sayem314 can you please revert it? The module specification should be kept as pure ts (or flow) as in my original PR... This is what allows codeGen to generate the JSI stuff correctly.

@ErHarinderSingh in the meantime, you can use my fork until @sayem314 fixes this...

**Comment by sayem314** [comment]
@zabojad Thank you. v1.2.2 published to npm.

**Comment by ErHarinderSingh** [comment]
Thanks @zabojad @sayem314 , No problem. I can wait today. I am waiting for new version come out of the box.
Thanks for understand things.
